### ISSUE TITLE
It crashes my mac sometimes

### ISSUE THREAD

**Issue by diogoviannaaraujo** [SylvainRX/OSX-NC-RemoteForKodi#1]
Sometimes, when I have just open notification center, the first button I press make my mac freeze and restart.

**Comment by SylvainRoux** [comment]
Thank you for your feedback, it seems pretty serious. Please, can you tell me what's your version of MacOS and Kodi ? Is it crashing kind of randomly or just in some cases? Beside that, does it function properly?
