### ISSUE TITLE
No way to configure the widget "i" missing

### ISSUE THREAD

**Issue by Shawzborne** [SylvainRX/OSX-NC-RemoteForKodi#3]
Hi,

I have the latest version of the widget and I am unable to configure the widget.

Not sure why username and password was left out of the widget on version 1 but if you can please add that and the "i" back to the widget that would be great.

I am running macOS Sierra 10.12

![screen shot 2016-06-22 at 10 17 46 am](https://cloud.githubusercontent.com/assets/5931778/16269984/98432c20-3862-11e6-9e62-5c662aea0484.png)
Thank-you,

Shawn

**Comment by SylvainRX** [comment]
http://forum.kodi.tv/showthread.php?tid=234920&pid=2363901#pid2363901

Thanks :)
