### ISSUE TITLE
Can't connect

### ISSUE THREAD

**Issue by maxgrass** [SylvainRX/OSX-NC-RemoteForKodi#4]
Hello I cannot connect to my Kodi (without password),
so I wanted to try to debug the project, however I encountered build errors:

clang: error: no such file or directory: '/Users/xxx/Documents/code/MacOS-NC-RemoteForKodi/Remote For Kodi/KodiRPC.m'

<img width="261" alt="screen shot 2018-03-22 at 23 31 52" src="https://user-images.githubusercontent.com/169885/37802076-3e8690dc-2e29-11e8-8c27-8e3c9107de70.png">

I could check which request (and whether) are being sent if you advise a tool for that.

**Comment by SylvainRX** [comment]
Hello Maxgrass,
I've looked it up on my old computer, and I can't find anything about this file.
I'm sorry about it. I hope you will manage to get it to work for your usage.
Thanks for your interest. Please keep me in touch if you succeed

**Comment by maxgrass** [comment]
ok, the problem was in the wrong port, the widget uses websockets, so the default kodi port is 9090. I tried the web interface's port. Thanks.
BTW the building problem was with referencing SocketRocket framework, I learned it halfway and compiled the App.
